name: Docker Build Check

on:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build (no push)
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          load: false
          platforms: linux/amd64
          provenance: false
          tags: local/claude-relay-service:pr-${{ github.event.pull_request.number || github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
