name: semantic-pr

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  semantic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          validateSingleCommit: false
          types: |
            feat
            fix
            docs
            style
            refactor
            perf
            test
            build
            ci
            chore
            revert
          scopes: |
            api
            web
            cli
            scripts
            services
            routes
            utils
            config
          requireScope: false
          subjectPattern: ^(?![A-Z]).+[^\.]$
          subjectPatternError: >-
            PR 标题需使用祈使句（非首字母大写、无句号结尾），示例：feat(api): add xxx

